

 @endpoint = http://localhost:3000/api/v1/cars 



### 


### Create a car
POST {{endpoint}} HTTP/3.0
content-type: application/json

{"make": "Toyota",
  "model": "Corolla",
  "year": 2020
}

###
GET  {{endpoint}} HTTP/3.0 

content-type: application/json 

 

### 

GET  {{endpoint}}/ HTTP/3.0 

content-type: application/json 

 
 

### 

 

DELETE  {{endpoint}}/6abe6115d81dea2645018206 HTTP/3.0 

content-type: application/json 

 

### 

 

PUT  {{endpoint}}/sillycarID HTTP/3.0 

content-type: application/json 
###

Get http://localhost:3000/api/v1/cars HTTP/3.0
Content-Type: application/json
x-api-key: blahblah

###
@openapi 
  /cars: 
    get: 
      summary: Retrieve all cars 
      tags: 
        - Cars 
     responses:
        200: 
          description: Successfully retrieved cars 
        500: 
  description: Internal server error 

 