

 @endpoint = http://localhost:3000/api/v1/cars 



### 


### Create a car
POST {{endpoint}} HTTP/3.0
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla"
}

### Get one car (use a real _id returned from the POST above)
GET {{endpoint}}/66f8a1b2c3d4e5f678901234 HTTP/1.1

### 
GET  {{endpoint}} HTTP/3.0 

content-type: application/json 

 

### 

GET  {{endpoint}}/sillycarID HTTP/3.0 

content-type: application/json 

 
 

### 

 

DELETE  {{endpoint}}/sillycarID HTTP/3.0 

content-type: application/json 

 

### 

 

PUT  {{endpoint}}/sillycarID HTTP/3.0 

content-type: application/json 